### ISSUE TITLE
文档链接错误

### ISSUE THREAD

**Issue by yugasun** [devsapp/website#1]
项目中 [docs/advance.md](https://github.com/devsapp/website/blob/master/docs/advance.md) 中的链接跳转到了 [tencent-examples](https://github.com/serverless-components/tencent-examples/tree/master/fullstack)
如下截图：
![image](https://user-images.githubusercontent.com/8536173/122498209-47adc200-d021-11eb-92e1-d63943f16c61.png)

**Comment by anycodes** [comment]
感谢，已经修复。
